### ISSUE TITLE
Points (nodes) are not rendered in changeset geometry

### ISSUE THREAD

**Issue by ppawel** [mapbox/owlviewer#14]
It's because the following code in the GeoJSON layer initialization:

```
 pointToLayer: function(featureData, latlng) {
        return new L.Polyline([latlng]);
    },
```

Apparently, polyline with one point is not rendered (as probably it is not valid).

**Comment by lxbarth** [comment]
This was a quick stop gap to avoid having leaflet standard markers show up on the map. Needs fixing.
