### ISSUE TITLE
Tiles not loaded while panning

### ISSUE THREAD

**Issue by ppawel** [mapbox/owlviewer#17]
I'm not sure if this is specific to summary tiles in my summary-tiles branch but go to the following URL and move the map in some direction:

http://suncobalt.dyndns.org:8082/owlviewer/index.html#5/51.234/15.535

The result is that only tiles near the edges are loaded.

**Comment by lxbarth** [comment]
Fixed. See https://github.com/mapbox/owlviewer/commit/6073af25bfbd6b707e49c80f252c2e79fe61458b#commitcomment-2119985
