### ISSUE TITLE
Tiles near the edges are NOT loaded

### ISSUE THREAD

**Issue by ppawel** [mapbox/owlviewer#18]
This is different to #17. Go to:

http://suncobalt.dyndns.org:8082/owlviewer/index.html#7/55.770/-2.324

You can see that tiles at the bottom edge are not loaded.

**Comment by lxbarth** [comment]
Fixed. See https://github.com/mapbox/owlviewer/commit/6073af25bfbd6b707e49c80f252c2e79fe61458b#commitcomment-2119985
