### ISSUE TITLE
Summary tiles seem misaligned

### ISSUE THREAD

**Issue by ppawel** [mapbox/owlviewer#20]
Take a look:

http://suncobalt.dyndns.org:8082/owlviewer/index.html#3/52.38/54.23

The tile with most changesets (46k at this time) is mostly on the water, Scandinavia and Iceland. This does not seem right.

Also, when you zoom in you can see that now 37k changesets is shown on a tile which covers UK and part of continental Europe.

This behavior continues as you zoom in.

**Comment by lxbarth** [comment]
Fixed with https://github.com/mapbox/owlviewer/commit/6073af25bfbd6b707e49c80f252c2e79fe61458b#commitcomment-2119985
