### ISSUE TITLE
Concepts for a more useful sidebar

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/owlviewer#4]
Here are three concepts for extending the usefulness of the sidebar.

First of all, as soon as feasible, we should [de-emphasize the changeset ID and make the changeset comment the title of the changeset](http://cl.ly/image/1r3f3v1o2S2N/o).

Secondly, it might be interesting to do a breakdown of the contents of changesets. Here's [a simple approach that just lists numbers](http://cl.ly/image/3n0s40092F3L/o). On the other hand, [we could do a visualization (with some sort of logarithmic scale) of the contents, with details on hover](http://cl.ly/image/0y1a2O0v2y21/o).

I actually keeping the listing view simple may be better. These additional details hurt overall scannability / legibilitiy of the listing. The best approach would be to keep the listing simple by default, and then implement an expanded view with more details on click, similar to the way tweets work on twitter. Look at [the default](http://cl.ly/image/1z342J3T2y0O/Screen%20Shot%202012-11-02%20at%201.56.23%20PM.png) vs [expanded](http://cl.ly/image/32382G1E3F0k/Screen%20Shot%202012-11-02%20at%201.56.25%20PM.png).

**Comment by lxbarth** [comment]
> I actually keeping the listing view simple may be better. 

Agreed. On that note I could see us get away with just showing the number of changes - enough for scanning the list.

>  Look at the default vs expanded.

Here I'm curious whether we need what Twitter does default/expanded/full view or whether we can get away with default/[full view](http://www.openstreetmap.org/browse/changeset/5) if the full view is fast enough.

**Comment by ppawel** [comment]
Wow, nice work! I think being able to identify the size of a changeset (at least relatively) just by looking at the list (without expanded details) would be a very needed feature.

So IMHO something like the simple list view (without details) + a simple changeset size/complexity indicator (icon? color?) would be best of both worlds.

**Comment by samanpwbb** [comment]
@ppawel Yeah, it might be possible to pull off a clever visualization that doesn't cut into scannability.  I will think harder about how to design this once we know we have the capability to implement it.

**Comment by samanpwbb** [comment]
[Had a quick idea and I couldn't resist mocking it up](http://cl.ly/image/2w0v3c2B3s0i)

The idea here is to simply color-code size with a 5px bar to the left of the listing, then slide in details on click. The interaction of course could be totally cut. The important concept is a simple color coded bar.

**Comment by ppawel** [comment]
@samanpwbb The idea with color-coding the size is great. However I think that maybe the mockups and interaction ideas should slowly be drifting towards osm.org. I mean obviously you have limited time to spend on this and I'm not sure if building concepts for extending a standalone owlviewer application even further is the best use of that time. I.e. while the last mockup is great I don't see how it could be easily integrated with the main site right now.

What do you think?

**Comment by samanpwbb** [comment]
I agree. The more elaboriate concepts here are definitely a low priority. That said:

1) I think it's a good idea to keep thinking about how to better visualize these changesets. Concepts can always be carried over to the main site if they feel good in the owl viewer.

2) If you get some of the pieces in place to do this kind of visualization, I can help out with the design / front end implementation.

**Comment by ppawel** [comment]
I added entity change counts to the API and also simple display to owlviewer (should be deployed at owl.osm.org within ~30 minutes). Desperately needs styling!
